# .readthedocs.yaml
version: 2

# Укажите версию Python, которую использует ваш проект
build:
  os: ubuntu-22.04
  tools:
    python: "3.13" # Укажите вашу версию Python

# Конфигурация Sphinx
sphinx:
  configuration: docs/conf.py # Путь к вашему conf.py

# Установка зависимостей Python
python:
  install:
    - requirements: requirements.txt 
